### ISSUE TITLE
Please create one working example "hello world"

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [FezVrasta/popper.js#730] opened 2018-12-07 12:30 UTC
The docs missing one simple example (Like most js plugins). Very annoying.

**Comment by FezVrasta** [comment] 2018-12-07 12:31
Doesn't this work for you?

https://popper.js.org/#example10

**Comment by Ezra-Siton-UIX** [comment] 2018-12-07 15:33
No. Full code (JS + `HTML`). For copy-paste. The docs missing "hello world" style - simple example.

**Comment by FezVrasta** [comment] 2018-12-07 15:35
I see, I'll accept a PR to add that, it should be added here:

https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/index.js#L143

**Comment by Ezra-Siton-UIX** [comment] 2018-12-07 15:37
Ok. In general most of the docs is like "html -- js (src) + initialize (Than by 10 seconds devX can start to work on plugin X with most basic example). 

Example from tippy:

JS src
```
<script src="https://unpkg.com/tippy.js@3/dist/tippy.all.min.js"></script>
```
html
```
<button>Text</button>
```
intilize
```
tippy('button', { content: "I'm a tooltip!" })
```

Thanks.

**Comment by FezVrasta** [comment] 2018-12-07 15:38
I understand, but I think this example is pretty eloquent already:

https://github.com/FezVrasta/popper.js#usage

**Comment by FezVrasta** [comment] 2018-12-07 15:40
I improved it adding an example HTML, but I'd still like to see it also on the website docs.

**Comment by Ezra-Siton-UIX** [comment] 2018-12-07 15:44
And where i find full basic example of `tooltip` - this only position the element:
https://codepen.io/ezra_siton/pen/QzLdYW

**Comment by FezVrasta** [comment] 2018-12-07 15:49
Popper.js is a positioning library, not a tooltip library. Use Tooltip.js if you want a complete tooltip.

**Comment by Ezra-Siton-UIX** [comment] 2018-12-07 15:50
OK. But where i find full example (for tooltip.js) -

**Comment by FezVrasta** [comment] 2018-12-07 15:58
https://popper.js.org/tooltip-examples.html

**Comment by Ezra-Siton-UIX** [comment] 2018-12-08 00:17
I saw this. First its hard to  know you should first include `popper` for `tooltip.js` to work (Use **both** files). Next no detials about the style of the `tooltip`. 

### tooltip.js basic example
For me this is good/basic starter. How to (Less than 1 minute to get working example):

**1. Including files**
```javascript
<script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
<script src="https://unpkg.com/tooltip.js/dist/umd/tooltip.min.js"></script>
```
**2. HTML structre**
To apply this component, add the `data-tooltip` attribute to an element. 
```html
<button id="hello-world" data-tooltip="hello world">Hover Me</button>
```
**3. Initialization**

```javascript
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var trigger = document.getElementById("hello-world");
    var instance = new Tooltip(trigger, {
      title: trigger.getAttribute('data-tooltip'),
      trigger: "hover",
      placement: "top",
      /* more options her */
    });
  });
</script>
```

4. Example of basic styling:
```CSS
<style>
.popper,
.tooltip {
  position: absolute;
  background: #ffc107;
  color: black;
  width: 150px;
  border-radius: 3px;
  box-shadow: 0 0 2px rgba(0, 0, 0, 0.5);
  padding: 10px;
  text-align: center;
}
</style>
```

Missing - basic example of "how to style the arrows"
https://codepen.io/ezra_siton/pen/QzLdYW

**Comment by compsult** [comment] 2019-05-04 15:06
What I would find helpful is a list of "if you want to do this, here is the code" For example, if you want to hide a popper, programmatically move a popper or change any popper attribute followed by a snippet

**Comment by Ezra-Siton-UIX** [comment] 2019-05-11 16:29
> What I would find helpful is a list of "if you want to do this, here is the code" For example, if you want to hide a popper or programmatically change a popper, this is the code to do it

You find pooper `methods` her:

```
<!-- Initialization set tooltip by js -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var referenceElement = document.getElementById("hello-world");
    
    var instance = new Tooltip(referenceElement, {
      title: referenceElement.getAttribute('data-tooltip'),
      trigger: "hover",
      placement: "top",
      /* more option her */
      /* #list of options: */
      /* https://popper.js.org/tooltip-documentation.html#new_Tooltip_new*/
    });    
    instance.show();    
  });
</script>
```
https://popper.js.org/tooltip-documentation.html#Tooltip+show

The same idea for other methods. 

About:
`Tooltip.TitleFunction ⇒ String`
Very hard to know what the idea behind.

**Comment by waspinator** [comment] 2019-05-26 12:29
Following the example listed in the docs, when the 'popper' overlaps the reference in stead of being "right" of it.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8' />
  <script src="https://unpkg.com/popper.js@1.15.0/dist/umd/popper.min.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var reference = document.querySelector('.my-button');
      var popper = document.querySelector('.my-popper');
      var popperInstance = new Popper(reference, popper, {
        placement: "right"
      });
    });
  </script>
</head>

<body>
  <div>
    <div class="my-button">reference</div>
    <div class="my-popper">popper</div>
  </div>
</body>
</html>
```

**Comment by Ezra-Siton-UIX** [comment] 2019-05-26 19:17
@waspinator - please Open a seperate GitHub issue. Looks like a bug (If you change the reference to button - the code works fine). 

`
<button class="my-button">reference</button >
`

**Comment by FezVrasta** [comment] 2019-06-02 08:43
Fixed in 8f2469111dcc483623a5fcba99e34c661f9ea74d

**Closed by FezVrasta** 2019-06-02 08:43 UTC
Labels: TARGETS: docs

**Comment by fabswt** [comment] 2019-07-19 13:38
I agree with the OP. The website feels like it was written for someone who already knows what it's all about, not someone getting started – it's lacking a *Getting started* page.

This is my second time trying to get into tooltip.js, this time I pulled through.

Some things that got in the way:

- Popper.js or Tooltip.js? Which one am I supposed to use? It's not obvious from the homepage. (It gets clearer on the GitHub README, but if the homepage is the starting point then it should be there.)
- What do they do?
  - Is any CSS part of it? e.g.: the yellow tooltips from the docs look nice, but they're apparently not part of the library itself. There are also no arrows out of the box (I see them in the markup, but again no CSS.)
  - Likewise: how do I style anything? Are there some classes I should use (and others I shouldn't touch) to be safe / future proof? Without such info it's down to hacking it away with the Inspector and there's no guarantee things won't break in a future version.
- Starting the documentation with a class definition is… uninviting. I'd much rather see a "Hello world" example, *from scratch*. (The sort of minimal complete reproducible examples folks expect on StackOverflow.)
- On Codepen, adding popper and tooltip via the JavaScript Pen settings results in these files being linked: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/popper.min.js and https://cdnjs.cloudflare.com/ajax/libs/tooltip.js/1.3.2/tooltip.min.js but they don't work (linking to the files on unpkg.com works fine), with the error:
> SyntaxError: export declarations may only appear at top level of a module popper.min.js:4:19633
> SyntaxError: import declarations may only appear at top level of a module tooltip.min.js:4:3

Sorry to be so negative, but hopefully you can see I'm trying to be constructive about it. 

I created a Codepen: [Tooltip.js hello world · Working example](https://codepen.io/fabswt/pen/wVBybm). It reproduces the styling seen in the docs (yellow tooltip + arrow) and the code is clear.

People seeing this thread may want to check out tippy which is an alternative to tooltip.js, is also based on popper, and includes more documentation, styling and examples.

**Comment by FezVrasta** [comment] 2019-07-19 16:08
@fabswt I see your point, unfortunately I don't have enough free time to allocate to the docs, I'm focusing all my time on the work needed to ship Popper.js v2.

If anyone wants to send PRs to improve the docs I'll be happy to merge them.

About the CDNJS issue, I'm not sure why that's happening, the default file should be the `umd` one, as pointed out in the `package.json` `main` field.

**Comment by henrypenny** [comment] 2019-10-15 21:50
It's frustrating hunting around the website looking for an example with css. At the least you could add one line early on that says: CSS not included. That will stop people hunting for something that's not there.

**Comment by FezVrasta** [comment] 2019-10-16 10:30
@henrypenny I'm still accepting PRs! Thanks!

**Comment by Ezra-Siton-UIX** [comment] 2019-10-16 11:05
@henrypenny the most basic example her:
https://codepen.io/ezra_siton/pen/QzLdYW

**Comment by henrypenny** [comment] 2019-10-16 19:46
Thanks @Ezra-Siton-UIX 

For those who come after me here's the example CSS:

```
.popper,
.tooltip {
  position: absolute;
  background: #ffc107;
  color: black;
  min-width: 150px;
  border-radius: 3px;
  box-shadow: 0 0 2px rgba(0, 0, 0, 0.5);
  padding: 10px;
  text-align: center;
}
.popper .popper__arrow,
.tooltip .tooltip-arrow {
  width: 0;
  height: 0;
  border-style: solid;
  position: absolute;
  margin: 5px;
}

.tooltip .tooltip-arrow,
.popper .popper__arrow {
  border-color: #ffc107;
}
.popper[x-placement^="top"],
.tooltip[x-placement^="top"] {
  margin-bottom: 6px;
}
.popper[x-placement^="top"] .popper__arrow,
.tooltip[x-placement^="top"] .tooltip-arrow {
  border-width: 5px 5px 0 5px;
  border-left-color: transparent;
  border-right-color: transparent;
  border-bottom-color: transparent;
  bottom: -5px;
  left: calc(50% - 5px);
  margin-top: 0;
  margin-bottom: 0;
}
.popper[x-placement^="bottom"],
.tooltip[x-placement^="bottom"] {
  margin-top: 6px;
}
.tooltip[x-placement^="bottom"] .tooltip-arrow,
.popper[x-placement^="bottom"] .popper__arrow {
  border-width: 0 5px 5px 5px;
  border-left-color: transparent;
  border-right-color: transparent;
  border-top-color: transparent;
  top: -5px;
  left: calc(50% - 5px);
  margin-top: 0;
  margin-bottom: 0;
}
.tooltip[x-placement^="right"],
.popper[x-placement^="right"] {
  margin-left: 6px;
}
.popper[x-placement^="right"] .popper__arrow,
.tooltip[x-placement^="right"] .tooltip-arrow {
  border-width: 5px 5px 5px 0;
  border-left-color: transparent;
  border-top-color: transparent;
  border-bottom-color: transparent;
  left: -5px;
  top: calc(50% - 5px);
  margin-left: 0;
  margin-right: 0;
}
.popper[x-placement^="left"],
.tooltip[x-placement^="left"] {
  margin-right: 6px;
}
.popper[x-placement^="left"] .popper__arrow,
.tooltip[x-placement^="left"] .tooltip-arrow {
  border-width: 5px 0 5px 5px;
  border-top-color: transparent;
  border-right-color: transparent;
  border-bottom-color: transparent;
  right: -6px;
  top: calc(50% - 5px);
  margin-left: 0;
  margin-right: 0;
}
```

**Comment by AJB99** [comment] 2019-12-02 09:51
I agree with all the other confused devs in this thread.

Why can't I find where I'm supposed to declare the `trigger` property on the `options` Object? How is it so difficult for me to figure this out that I'm thinking of just rolling my own popover comp?

Your docs are especially confusing because you've used a syntax that is overly-decorative, and seems to be missing 80% of the options that can actually be used with popper.js.

A quick example would be: Why is there a tilde prefixed to any Object property name? Could you not just display an example of the `options` Object with code-syntax styling so we can just see where we're supposed to declare the `options` and their values?

**Comment by FezVrasta** [comment] 2019-12-02 11:05
Tooltip.js is deprecated, please use Tippy.js, it has great docs.
