### ISSUE TITLE
Blurry content (text)

### ISSUE THREAD

**Issue by akinuri** [FezVrasta/popper.js#682] opened 2018-09-05 12:19 UTC
### CodePen demo

https://codepen.io/anon/pen/JayXEE

### Steps to reproduce the problem

1.  View demo on Chrome 68 (Windows 10).
2.  Hover the `refEl`.
3.  Observe the blurry tooltip text.
4.  In case the problem doesn't occur, I should further desribe my specs. I'm on a laptop with screen dimensions of 1920x1080 at scale %125.

### What is the expected behavior?

Text should look clear, free of distortion (blur).

### What went wrong?

Text looks blurry on Chrome 68.

### Any other comments?

`transform: translate3d(498px, 78px, 0px);` seems to cause the problem. Using `left` and `top` instead of `transform` solves the problem. So I'm wondering is there a particular reason behind using transform instead of left and top? If the reason is arbitrary, it'd be nice to have it optional.

PS: This might be a Chrome specific problem. Text looks all right in Firefox.

**Comment by FezVrasta** [comment] 2018-09-06 07:19
You can use the `disableGpuAcceleration` to get the same result...

**Comment by akinuri** [comment] 2018-09-06 11:50
Hmm. I've just searched for `disableGpuAcceleration` in both [popper.js](https://unpkg.com/popper.js@1.14.4/dist/umd/popper.js) and [tooltip.js](https://unpkg.com/tooltip.js@1.3.0/dist/umd/tooltip.js) and I don't see a prop/switch with that name. What am I missing?

**Comment by FezVrasta** [comment] 2018-09-06 16:05
https://popper.js.org/popper-documentation.html#modifiers..computeStyle.gpuAcceleration

**Comment by FezVrasta** [comment] 2018-09-12 12:06
Closing because it's a browser bug, and there is an option to fix it already, if needed.

**Closed by FezVrasta** 2018-09-12 12:06 UTC

**Comment by ahmadalfy** [comment] 2019-05-14 00:05
@FezVrasta another solution would be to round or ceil the value of the `transform3d`. The issue is clearly caused by the subpixels calculated.

**Comment by FezVrasta** [comment] 2019-05-14 05:32
We already round/ceil the values

**Comment by b-strauss** [comment] 2020-08-24 13:47
> We already round/ceil the values

The values are not rounded in my case (version: 2.2.4):

![image](https://user-images.githubusercontent.com/6588177/91051551-8d2b7980-e620-11ea-8a30-2a2f85ffe3aa.png)
![image](https://user-images.githubusercontent.com/6588177/91051748-d2e84200-e620-11ea-995d-121bc48da0f1.png)

If I round the values in the dev tools it looks ok:

![image](https://user-images.githubusercontent.com/6588177/91051869-fe6b2c80-e620-11ea-86c8-5255920306e0.png)
![image](https://user-images.githubusercontent.com/6588177/91051944-13e05680-e621-11ea-9b93-c9c361179cb3.png)

**Comment by ahmadalfy** [comment] 2020-08-24 15:38
@FezVrasta then maybe provide an option to opt-out of that at all?

**Comment by FezVrasta** [comment] 2020-08-24 15:39
https://popper.js.org/docs/v2/modifiers/compute-styles/#gpuacceleration
