### ISSUE TITLE
Popper is trapped in scrolling container

### ISSUE THREAD

**Issue by aristidesfl** [FezVrasta/popper.js#281] opened 2017-05-19 12:29 UTC
### CodePen demo

http://codepen.io/anon/pen/oWaPZV

### Steps to reproduce the problem

1.  Popper inside scrollable area
2.  Scroll gray content area

### What is the expected behavior?

Popper should `escapeWithReference` when reference completely goes outside container.

### What went wrong?

Popper is trapped in scrolling container

**Comment by FezVrasta** [comment] 2017-05-19 12:32
Dupe of #230

**Closed by FezVrasta** 2017-05-19 12:32 UTC
