### ISSUE TITLE
poor scrolling situation with position:fixed navbar

### ISSUE THREAD

**Issue by giladgray** [FezVrasta/popper.js#352] opened 2017-07-13 11:40 UTC
### CodePen demo

https://codepen.io/giladgray/pen/MoLrmV

![popover2-bad-scroll](https://user-images.githubusercontent.com/464822/28164518-713f18a4-67d8-11e7-9264-dae0e6e4a87d.gif)

### Steps to reproduce the problem

1. have a very long body that scrolls
1.  attach a popper to an element inside a `position: fixed` container (say, a navbar at the top)
2.  scroll the body
3.  watch the popper jump around

### What is the expected behavior?

Popper sits exactly where it is because the reference is not moving.
Popper should probably also be `position: fixed`.

### What went wrong?

Popper uses `position: absolute` and therefore must recompute positioning in each frame.

**Comment by FezVrasta** [comment] 2017-07-13 11:43
dupe of #264

**Closed by FezVrasta** 2017-07-13 11:43 UTC

**Comment by dcorb** [comment] 2017-09-29 15:24
@FezVrasta  Would it be possible to use a 3rd party modifier to apply position:fixed and warranty no jumping? I haven't write before a modifier, but if you think is a viable solution, I will investigate further

**Comment by FezVrasta** [comment] 2017-09-29 15:32
Yes ideally you could write a modifier for that, but I don't think it's going to be an easy task.
