### ISSUE TITLE
'Placement: bottom' makes popper sticky in scroll-container

### ISSUE THREAD

**Issue by markusdittrich** [FezVrasta/popper.js#560] opened 2018-02-20 22:59 UTC
### CodePen demo

Example 1: https://codepen.io/MarkusDittrich/pen/mXxNrQ
Example 2: https://codepen.io/MarkusDittrich/pen/ZrxgGW

### Steps to reproduce the problem

1.  Open Example 1; Scroll content; The popper (placement:'right') stays with the reference-element
2.  Open Example 2; Scroll content; The popper (placement:'bottom') sticks to the top of the screen

### What is the expected behavior?
I would have expected that the popper in example 1 would also stick to the top of the screen.

### What went wrong?
The different placement seems to throw it off.

### Any other comments?
What I'm actually looking for is a way to control this behaviour. I'd like to be able to have a popper with placement:right that sticks to the top and a popper with placement:bottom that stays with the reference-element. (And vice-versa)

**Comment by FezVrasta** [comment] 2018-02-21 11:16
That's a dupe of #230

It's the `keepTogether` modifier that makes the popper stick to its reference element in the first example.

https://codepen.io/FezVrasta/pen/GQdvBL

**Closed by FezVrasta** 2018-02-21 11:16 UTC

**Comment by markusdittrich** [comment] 2018-02-21 17:15
Perfect. Thanks for the quick reply!
