### ISSUE TITLE
Add `scrollingParent` as `boundariesElement` option

### ISSUE THREAD

**Issue by nadiam84** [FezVrasta/popper.js#59] opened 2016-07-19 06:33 UTC
Hello,

I'm having an issue with Popper inside a scrollable parent. It behaves weird. Could you maybe take a look? 

### CodePen demo

https://codepen.io/nadiam84/pen/LkQdLW

Another one with flex alignments and all positions (just in case)
http://codepen.io/nadiam84/pen/GqQbor

To make it more fun, Popper behaves perfectly inside a scrollable parent which is inside a parent with position 'fixed'.
http://codepen.io/nadiam84/pen/rLJEWg

### Steps to reproduce the problem

Just scroll vertically

**Comment by FezVrasta** [comment] 2016-07-19 09:23
Can you confirm that the problem is caused by the big margin applied to the target?

**Comment by nadiam84** [comment] 2016-07-19 10:43
Doesn't look like it. Updated the CodePen, made it without margins. Still the same issue.

**Comment by FezVrasta** [comment] 2016-07-20 08:34
The 2nd and 3rd examples work correctly, right?

**Comment by nadiam84** [comment] 2016-07-20 10:21
1st and 2nd are wierd, 3rd is working correctly

**Comment by FezVrasta** [comment] 2016-07-20 11:46
Disabling `preventOverflow` the problem is fixed so I guess it could be related to #58

**Comment by FezVrasta** [comment] 2016-08-08 10:02
Ok the problem is not realted to #58, I'm gonna investigate it right now.

**Comment by FezVrasta** [comment] 2016-08-08 10:10
The first example doesn't work because it's using `viewport` as boundaries element, but it's inside a scrolling div. Setting as boundariesElement the scrolling div everything works fine.
How would you solve this problem? Automatically setting the `boundariesElement` to the scrolling div or just asking users to properly define the boundaries?

https://codepen.io/FezVrasta/pen/akQpbW

**Comment by nadiam84** [comment] 2016-08-22 05:49
@FezVrasta  Popper behaves a bit weird inside a scrollable container (alfa-version).

https://codepen.io/nadiam84/pen/grywdy

When it's scrolled vertically, it waits when the parent will be completely hidden, and only than start to move itself. When it's scrolled horizontally, it doesn't go away at all.

Is there a way to make it permanently attached to its refElement? Isn't 'keepTogether' options suppose to do this?

**Comment by FezVrasta** [comment] 2016-08-22 06:19
I don't think I understand where the problem is, it seems everything correct to me.

May you try to describe what would you expect? Could you record a small clip to let me see if the behavior is different on your computer? (I suggest Licecap to record gifs)

**Comment by nadiam84** [comment] 2016-08-22 06:25
Here is gif:
https://goo.gl/photos/QLrxiJD1T5nTAGHD6

When I scroll vertically I expect popper to move with the parent always
Same with horizontally

**Comment by FezVrasta** [comment] 2016-08-22 06:29
You should disable the `preventOverflow` then

**Comment by FezVrasta** [comment] 2016-08-22 06:35
https://codepen.io/anon/pen/xONkxV

**Comment by nadiam84** [comment] 2016-08-22 06:41
But there is no flipping in this scenario :(
Ideally, I want something like this: https://goo.gl/photos/5aS6GDKggCiSuejb9

**Comment by FezVrasta** [comment] 2016-08-22 06:45
I have to play a bit with it to find a way. I'll let you know within the day

**Comment by nadiam84** [comment] 2016-08-24 07:54
@FezVrasta Any news? :)

**Comment by FezVrasta** [comment] 2016-08-24 08:08
Oh right, I guess this "day" is dragging for too long 😅 Looking at it right now.

**Comment by FezVrasta** [comment] 2016-08-24 08:16
https://github.com/FezVrasta/popper.js/issues/78

**Comment by FezVrasta** [comment] 2016-09-18 21:04
To summarize, we need to add `scrollingParent` as allowed `boundariesElement` value.

This will be the new default value and will always point to the closest scrollable parent (`overflow !== initial`)

**Comment by FezVrasta** [comment] 2016-10-10 10:34
Closing this in favor of #74.

**Closed by FezVrasta** 2016-10-10 10:34 UTC
Labels: ENHANCEMENT, MODIFIER, PR WELCOME
