### ISSUE TITLE
Popper moves out of viewport when resizing

### ISSUE THREAD

**Issue by Falingorn** [FezVrasta/popper.js#58] opened 2016-07-07 06:43 UTC
Hey there,

at first, popper.js is really nice and I try to use it instead of tether.io owing to performance problems.
It works quite well, but there is a problem when resizing the viewport, which I tried to understand and solve for some hours now.

The problem is as follows. Open the popover and now resize the browser width. At a specific point, the popover moves to the right. This leads to a positioning problem in some viewports, where the popover is fully shown, but the positioning is wrong. I would expect, that the popover pins to the right side of the viewport when resizing.

For a better understanding, here's the [Codepen](http://codepen.io/anon/pen/NAvqmq). 

Thanks for your suggestions and hope we find a solution together.

Kind regards,
Falingorn

**Comment by FezVrasta** [comment] 2016-07-07 10:49
It's the `preventOverflow` modifier that kicks in when it shouldn't...

A temporary fix is to disable this modifier:
http://codepen.io/FezVrasta/pen/Lkjjqb

But the modifier should be fixed.

**Comment by Falingorn** [comment] 2016-07-11 09:58
Thanks a lot 👍  ... I'll probably use it as you suggest and try to fix it later on if I'll get a timeframe for this.
Happy coding! :)

**Comment by FezVrasta** [comment] 2016-08-07 13:56
@Falingorn had you a chance to look at this problem?

**Comment by FezVrasta** [comment] 2016-08-08 09:44
I'm digging into it, seems like the problem is the `arrow` modifier, not `preventOverflow`

**Comment by FezVrasta** [comment] 2016-08-08 09:55
Ok found the problem, in your example, the arrow element has not style, this makes the arrow wide as the popper, and creates the problem you describe.

You should not add an arrow if you don't want to use it, or give a width to the arrow to make it work properly.

http://codepen.io/FezVrasta/pen/ZOmBkQ


I'm closing it for now because it doesn't seem like a bug of the library but a misconfiguration. If you have any idea to avoid this problem let me know.
For now I'd say: Don't use arrow if you don't want to display one.

**Closed by FezVrasta** 2016-08-08 09:55 UTC
Labels: BUG, MODIFIER, PR WELCOME

**Comment by Falingorn** [comment] 2016-08-09 07:45
Thanks a lot ... will try it.
Is there a possibility to decide via configuration options if popper has an arrow or not? I think this would be a better approach than solve this with css.

You rock man! ;)

**Comment by FezVrasta** [comment] 2016-08-09 08:34
you can set `arrowTagName` to `undefined` to avoid the creation of the arrow element.

**Comment by ArtemKolychev** [comment] 2021-12-07 07:22
I have to same problem in version "@popperjs/core": "^2.11.0"
node 10.
framework Vue 2
```
createPopper(document.querySelector(...), document.querySelector(...), {
        placement: 'bottom',
        modifiers: [...], // offset[0,5]
      });
```

**Comment by ArtemKolychev** [comment] 2021-12-07 09:59
Ok. I fix it. You need wrap your's trigger div with position: absolute
```
<div style="position: absolute">
    <i
      class="icon-custom icon-custom--info"
    />
    <div
      :style="..."
      role="tooltip"
    >
      <slot name="content"/>
      <div
        id="arrow"
        data-popper-arrow/>
    </div>

  </div>
```
