### ISSUE TITLE
Tooltip Positioning Issue

### ISSUE THREAD

**Issue by davcpas1234** [FezVrasta/popper.js#457] opened 2017-10-14 13:02 UTC
### Issue
When integrating with Bootstrap (if this needs to be logged with BS please let me know), I've noticed that when I set a container's min-height programmatically or statically to fill the viewport, the positioning of any tooltips within this container go off-center.

### CodePen demo

https://codepen.io/davcpas1234/full/KXxYdZ/

### Pre-requisites

1. Requires "a" wrapper element to have `min-height` calculated by jQuery to be equal to 100%

### What is the expected behavior?

Tooltip is displayed in correct position relative to element (a button in this example)

### What went wrong?

Tooltip is displayed off-center (screenshot from codepen):
![tooltip-issue](https://user-images.githubusercontent.com/3764587/31575896-38803b7a-b0e8-11e7-969f-4463a95d70c0.png)

Positioning resolves if resized when "displayed"
![tooltip-issue](https://user-images.githubusercontent.com/3764587/31575789-35c58f04-b0e6-11e7-8edb-5b25015a25ab.gif)

I'm suspecting that this has something to do with the scrollbar, as when the scrollbar is displayed the tooltips are displayed in the correct position:
![codepen io-davcpas1234-pen-kxxydz](https://user-images.githubusercontent.com/3764587/31575928-bbf36680-b0e8-11e7-9656-44d94fde188f.png)

### Any other comments?

- Tested on Chrome 61.0.3163.100
- Tested on Edge
- Tested on Chrome Canary 63.0.3239.5

**Comment by FezVrasta** [comment] 2017-10-18 10:16
I can't reproduce on Chrome 61

![image](https://user-images.githubusercontent.com/5382443/31713309-2c5cc368-b3fe-11e7-9b6f-3d1691db840e.png)

**Comment by davcpas1234** [comment] 2017-10-24 10:48
Hi @FezVrasta, I've updated the code pen. This issue is reflected correctly. Apologies!

![image](https://user-images.githubusercontent.com/3764587/31939108-506982b6-b8b1-11e7-8585-b3569a5df324.png)

**Comment by davcpas1234** [comment] 2017-10-24 10:55
I've created an additional codepen with a workaround, for my specific example: https://codepen.io/davcpas1234/pen/full/OxeJXN

If I force the JS to apply a 1px overflow, the tooltips are positioned correctly:
![image](https://user-images.githubusercontent.com/3764587/31939413-358658ba-b8b2-11e7-9007-36fd67df57cf.png)

**Comment by davcpas1234** [comment] 2017-10-24 11:04
Side by side:

![image](https://user-images.githubusercontent.com/3764587/31939726-66cb2274-b8b3-11e7-9069-a55855ba4413.png)

Hopefully this helps @FezVrasta 👍

**Comment by ctian1** [comment] 2017-10-30 23:52
Also experiencing this.

**Comment by FezVrasta** [comment] 2017-10-31 06:46
I still can't reproduce it... Do I have to do something specific?

**Comment by michalduda** [comment] 2017-11-16 15:47
Hey.

I'm also experiencing this problem. 

At first I was pretty confused cause the problem appeared only on the external monitor, not on my laptop’s screen. I could drag the same browser window from one to another and the behaviour of the tooltips changed. On the bigger screen tooltip is always shifted to the left – just about 17px.

So I’ve checked if it is somehow connected with the vertical scrollbar and the answer is “yes”.
When there is no scrollbar – the tooltips are shifted to the left. 

This codepen shows the issue for me - but only without the scrollbar present. 

https://codepen.io/davcpas1234/full/KXxYdZ/

Do you have any idea why?

**Comment by FezVrasta** [comment] 2017-11-16 19:50
Are you on Windows?

**Comment by michalduda** [comment] 2017-11-17 12:06
Yes, Windows 10 x64.
I've tested it on Chrome 62, Firefox 56 and Edge 15.

Also tested on 3 other PCs (Windows 7 and 10, Chrome, from my colleagues at work) and the bug shows in every case.
Are there any more details that I can share?

**Comment by FezVrasta** [comment] 2017-11-17 12:07
If you could record a little clip to show me how you reproduce it and how you don't it would be awesome.

You may use https://www.cockos.com/licecap/

**Comment by michalduda** [comment] 2017-11-17 12:33
Sure, here it is: 

![nov-17-2017-1_23-pm](https://user-images.githubusercontent.com/8058615/32947256-50b827de-cb9b-11e7-970b-8c54b7845d91.gif)

Also, as davcpas1234 mentioned in the first post, when you resize the window when the tooltip is displayed - the position gets fixed and the tooltip is centered as it should.

**Comment by davcpas1234** [comment] 2018-01-01 16:32
This issue is potentially linked to the below:
https://github.com/twbs/bootstrap/issues/25013
https://github.com/FezVrasta/popper.js/issues/510

**Comment by kjdion84** [comment] 2018-01-01 19:38
@davcpas1234 Yep, and I'm even considering using a seperate library for tooltips because of this. Really annoying. Has anyone found a quick fix for this yet?

**Comment by kjdion84** [comment] 2018-01-01 21:24
Even calling `.tooltip('update')` does not correct the issue.

**Comment by danwad** [comment] 2018-02-15 15:34
@FezVrasta Here is a minimal reproduction using `min-height: 100vh` on the container.

https://codepen.io/anon/pen/paWMeV/

Version 63.0.3239.132 (Official Build) (64-bit) on macOS 10.13.3

**Comment by YoranBrondsema** [comment] 2018-02-22 14:11
I was seeing a similar issue and I figured out the root cause.

As was said previously, the situation arises when an element on the page has as height the entire viewport (`100vh`). Imagine the following DOM:

What happens is that right before the computation of the position of the popper, the popper gets `position: absolute`. However, since the popper appears after the page in the DOM, it will be positioned after it as well. Since the height of the page then becomes `100vh + height(popper)`, the scrollbar appears. This can be seen on https://codepen.io/anon/pen/zRaaLa.

So right before the position is computed, the scrollbar appears (whereas it was invisible before). As you can imagine, this messes it up and this is why the positioning is shifted just by the width of the scrollbar. After the computation is done, the popper is positioned and so the scrollbar disappears.

### Solution 1 (in client): place the popper element before any element on the page that has a `100vh` height.
See https://codepen.io/anon/pen/rJKKoK for why this works.

### Solution 2 (in client): set `top: 0` on the popper
This would force the positioning of the popper while the computation is done. After, this property would be overridden as the library sets a `top` property in the `style` attribute.

@danwad Here is a modified fork of you Codepen where this fix is applied: https://codepen.io/anon/pen/GQGGmV.

### Solution 3 (in library): 
Alternatively, I managed to fix it by surrounding the line https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/methods/update.js#L29 (call to `getReferenceOffsets`) with:

```
this.popper.style.top = 0;
data.offsets.reference = getReferenceOffsets(...);
this.popper.style.top = null;
```

This prevents the scrollbar from appearing when it matters, i.e. when computing the reference offsets. However, I'm not 100% sure that this fix won't mess up some other edge cases.

I hope this helps!

**Comment by FezVrasta** [comment] 2018-02-22 14:14
@YoranBrondsema could we set `top` to 0 before this line maybe?

https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/modifiers/applyStyle.js#L52

**Comment by YoranBrondsema** [comment] 2018-02-22 14:25
@FezVrasta Yes, that would actually even be better as you would only do it once. Once the `top` is set, it is never reset right?

**Comment by FezVrasta** [comment] 2018-02-22 14:27
The value of `top` will be overridden depending by the settings used by Popper.js, if `gpuAcceleration` is set to `false` it will be replaced with the top offset of the popper, if set to true, it will stay set to `0`.

Feel free to send a PR.

**Comment by travislaynewilson** [comment] 2018-03-22 16:33
FYI, this is also happening to me when I place the element as the last element in the body, while I have the height of <body> and <html> as 100%.

**Comment by FezVrasta** [comment] 2018-04-03 12:08
Closing as dupe of #510, I think this is the only plausible solution?

**Closed by FezVrasta** 2018-04-03 12:08 UTC
Labels: # BUG, DIFFICULTY: medium, PRIORITY: medium, TARGETS: core

**Comment by somnetics** [comment] 2024-03-28 09:56
Solution 2 (setting top in the CSS) worked great for me!
