### ISSUE TITLE
.tooltip doesn`t change opacity on hover

### ISSUE THREAD

**Issue by Krasnov8953** [FezVrasta/popper.js#625] opened 2018-05-04 13:43 UTC
Can`t make plugin work because on hover .tooltip is still opacity: 0

I use webpack

**yarn.lock**
`tooltip.js@^1.2.0:
  version "1.2.0"
  resolved "https://registry.yarnpkg.com/tooltip.js/-/tooltip.js-1.2.0.tgz#8b16482f04397f4f9d7387843dccf186890c8860"
  dependencies:
    popper.js "^1.0.2"`

**tooltip.js**
```
import Tooltip from 'tooltip.js'
$( () => {
  const $element = $('.js-tooltip')
  const title = $element.data('text')

  const tooltip = new Tooltip($element[0], {title, trigger: 'hover', placement: 'top'})
  $element.mouseenter(() => tooltip.show())
})
```

**Comment by FezVrasta** [comment] 2018-05-04 13:43
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Closed by FezVrasta** 2018-05-04 13:43 UTC

**Comment by vindemasi** [comment] 2018-10-06 10:09
hello @Krasnov8953 
are you using bootstrap? IMHO the issue is here because 'show' class is missing

[https://github.com/twbs/bootstrap/blob/v4-dev/scss/_tooltip.scss#L13](url)

opacity stay to 0 value ever.

```
  opacity: 0;

  &.show { opacity: $tooltip-opacity; }
```
