### ISSUE TITLE
For preventOverflow.padding can you overload to accept an array or string

### ISSUE THREAD

**Issue by BrianBu01** [FezVrasta/popper.js#613] opened 2018-04-11 22:29 UTC
When having a sticky footer, the viewport of my ui is padded at the bottom.  The prevent overflow doesn't have an easy way to apply the padding on just the bottom to apply an artificial boundary.  I need a 100px boundary just to be applied to the bottom.  If the padding could also accept an array or a string such as css '0 0 100px 0' this would help greatly.

### What is the expected behavior?

new feature

### What went wrong?

boundaries are not always enough

**Comment by FezVrasta** [comment] 2018-04-12 08:02
Dupe of #518

**Closed by FezVrasta** 2018-04-12 08:02 UTC
