### ISSUE TITLE
window.perfomance is undefined on Safari 9

### ISSUE THREAD

**Issue by rafaelverger** [FezVrasta/popper.js#80] opened 2016-08-26 01:14 UTC
### Steps to reproduce the problem

1.  Open https://popper.js.org on Safari
2.  Scroll page to till poppers part

### What is the expected behavior?
Poppers should appears on target's boundaries.

### What went wrong?
Poppers appears on top=0 from the closest element with position: relative

### Any other comments?
Also, you can see error about window.performance on devtools console
![image](https://cloud.githubusercontent.com/assets/588697/17990998/39450aae-6b11-11e6-9086-893c40e8b255.png)

**Comment by FezVrasta** [comment] 2016-08-26 11:02
Can you specify the complete version of Safari and the version of macOS?

It works correctly on Safari 9.1.2 (11601.7.7) and macOS 10.11.6 (15G31)

**Comment by FezVrasta** [comment] 2016-08-26 14:40
it's supported from version 8 of Safari according to caniuse data:

http://caniuse.com/#search=performance.now

**Comment by rafaelverger** [comment] 2016-08-26 17:33
I've seen it on Safari 9.1.2 and OSX 10.9. I've also checked on caniuse and it do say that it works, but I didn't see working :(

Maybe an error with my OS version?

**Comment by FezVrasta** [comment] 2016-08-26 18:28
Can you reproduce it or it was just one time error? Does it work if you use Popper in any other environment (codepen, local html etc)?

**Comment by rafaelverger** [comment] 2016-08-27 18:53
It happens a every time. In my project, running local, I got the same error :/

**Comment by rafaelverger** [comment] 2016-08-27 18:58
I've tested it on my friend's macbook, with El Captain and Safari 9.1.2 and it worked... probably an error with my combination of safari+osx 😢

**Comment by rafaelverger** [comment] 2016-08-27 19:00
http://stackoverflow.com/questions/32937405/window-performance-now-is-undefined-in-safari-9

**Comment by FezVrasta** [comment] 2016-08-27 20:07
Ok closing since it's not a problem of popper. Feel free to send a PR with a performance.now polyfill if you want

**Closed by FezVrasta** 2016-08-27 20:07 UTC
