### ISSUE TITLE
Tooltip.js with placement:left flips to the right side in a position:relative parent while there is still space on the left side.

### ISSUE THREAD

**Issue by yk1711** [FezVrasta/popper.js#199] opened 2017-04-07 15:47 UTC
### CodePen demo

http://codepen.io/anon/pen/oZrzrK

### Steps to reproduce the problem

1.  Position Tooltip reference element inside a `position:relative` parent with `placement: left`

### What is the expected behavior?

I would expect the tooltip to not flip to the right as long as there is space in the viewport/body to show it.

### What went wrong?

The Tooltip flips to the right. When `position: relative` is removed from the parent, the tooltips shows to the left as expected.

### Any other comments?

I'm not sure if this is expected behavior, but in that case I'm sure there would be an option to ignore the parent's boundaries and use the whole viewport as boundary ? I tried setting `boundariesElement` to viewport/window, but same result.

**Comment by FezVrasta** [comment] 2017-04-07 15:50
Seems like a dupe of https://github.com/FezVrasta/popper.js/issues/199

**Closed by FezVrasta** 2017-04-07 15:50 UTC
Labels: # DUPLICATE

**Comment by yk1711** [comment] 2017-04-07 15:58
I did read #188 , wasn't sure if it applied here also. :)

Thanks for the cool plugin, btw. I can imagine how hard it is to create a positioning engine that can handle every scenario and perform in 60fps.. 👍 

Do you have any quick workarounds in mind other than removing position:relative from the parent for the time being ?

**Comment by FezVrasta** [comment] 2017-04-07 16:01
So, the hard part in the Popper.js work is to compute the position of the popper when it's placed in "weird" contexts (like yours).

You usually can solve the problem moving the popper element up in the three in a "less weird" place:

https://codepen.io/FezVrasta/pen/LWKbJN

**Comment by yk1711** [comment] 2017-04-07 17:43
Thanks, that has fixed all my positioning issues!
From your experience, any reason one would not want the popper be in the body ? I guess it relates to libraries like react and others that handle the dom themselves, so you want the popper content be in the container controlled by react instance where it's reactive to the data. I'm developing in Vue.js now and don't see a problem in placing the popper in the body, I just need to re-init the Popper instance each time the underlying data for the content changes in my Vue instance.

**Comment by FezVrasta** [comment] 2017-04-07 17:46
Yes that's one of the reasons, but others are:

1. Accessibility
1. Performance (in some cases)
1. Ability to make the poppers scroll inside a scrollable parent
1. more?
