### ISSUE TITLE
Popper misaligned when parent is fixed

### ISSUE THREAD

**Issue by nblackburn** [FezVrasta/popper.js#176] opened 2017-02-23 11:43 UTC
I have a popper targeted on a input field which is triggered when results are found based on the input (as sort of autocomplete) but instead of the popper being positioned to the target is showing up at the bottom right of the modal despite having boundaries etc...

Positioning the modal absolutely seems to make the popper snap to the right place so feel it's related to the fact both the modal and the popper are fixed in place.

**I am having a hard time isolating the reason this happens so am unable to provide a codepen at this time.**

### What is the expected behavior?

Popper should be aligned to the target.

![Expected](https://i.imgur.com/FzGFZLj.png)

### What went wrong?

Popper is positioned to the bottom right of the modal.

![Preview](https://i.imgur.com/dcJBiN6.png)

**Comment by FezVrasta** [comment] 2017-02-23 11:47
As pointed out [here](https://github.com/FezVrasta/popper.js/issues/172#issuecomment-281712028) looks like that changing an option of Popper fixes the problem but I can't help further without a minimal example that allows me to debug Popper.

I'm closing this for now, please as soon you have a reproducible example post it here and I'll reopen it. Does it sound good to you?

**Comment by nblackburn** [comment] 2017-02-23 11:49
I tried the boundary option but that doesn't appear to be honored.

**Comment by FezVrasta** [comment] 2017-02-23 11:52
In the codepen I provided I see this result:
![image](https://cloud.githubusercontent.com/assets/5382443/23258083/ec41d882-f9c6-11e6-99ed-6730e7ccc3c0.png)

Isn't it the expected?

**Comment by nblackburn** [comment] 2017-02-23 11:53
@FezVrasta Ignore that because it doesn't accurately reflect the issue.

**Comment by FezVrasta** [comment] 2017-02-23 12:01
okay, then I'm closing for now, once you have a reproducible example, post it here and we'll see what we can do.

**Closed by FezVrasta** 2017-02-23 12:01 UTC
Labels: INFO NEEDED

**Comment by nblackburn** [comment] 2017-02-23 15:20
I don't seem to be able isolate this issue, really having a hard time tracking it down into something obvious.

**Comment by FezVrasta** [comment] 2017-02-23 15:24
I'm sorry, I hope you understand that without an isolated issue I can't spend time debugging someone else code hoping to find out that the bug is related to my library and not to someone else code.

**Comment by nblackburn** [comment] 2017-02-23 15:28
I do understand, but at the same time it seems in relation to the two things when used together that creates the problem and so far have been unable to separate the two.

**Comment by FezVrasta** [comment] 2017-02-23 15:31
Popper.js works on simple DOM and CSS properties, any bug related to it can be reproduced without any external/additional JavaScript. You may start copying the markup and the CSS that generates the problem, and remove parts of it gradually until you find out what's causing the problem.

At that point, I can look at it and debug the library to fix it.

**Comment by nblackburn** [comment] 2017-02-23 15:32
http://codepen.io/nblackburn/full/KWKdva - this is the closest i have got to replicating it (start maximized, shrink the window and then go back to maximized again).

There definitely isn't something right about that.

**Comment by FezVrasta** [comment] 2017-02-23 15:44
I get a white page when I load that pen 🤔

**Comment by FezVrasta** [comment] 2017-02-23 15:47
Now it loads and looks good to me:
![image](https://cloud.githubusercontent.com/assets/5382443/23266295/b29a53ae-f9e7-11e6-9dcd-d53151cbfd20.png)

**Comment by nblackburn** [comment] 2017-02-23 15:50
@FezVrasta I am working on stripping stuff out, its seems now the javascript was removed for the UI library, it is working fine.

**Comment by FezVrasta** [comment] 2017-02-23 15:55
Check out what CSS/HTML that library adds, it may add some `transform: something` on a parent element and break everything.

**Comment by nblackburn** [comment] 2017-02-23 16:00
@FezVrasta That's the thing, it's not adding much at all

**Comment by nblackburn** [comment] 2017-02-23 16:39
There are transforms added to `.uk-modal-dialog`

```css
transform: translateY(-100px);
```

**Comment by nblackburn** [comment] 2017-02-23 16:50
@FezVrasta It's because the class is applied dynamically and popper doesn't know about it that causes the issue.

**Comment by FezVrasta** [comment] 2017-02-23 17:23
Ok if this is the case, this is a dupe of #172 as you said initially, but has nothing to do with `position: fixed`.

**Comment by nblackburn** [comment] 2017-02-23 19:18
@FezVrasta Nope it isn't related to position fixed as i originally said but was right about it being related.

**Comment by nblackburn** [comment] 2017-03-08 16:39
I am still convinced the error does in fact relate to both `reference` and `popper` being `position: fixed;` because upon changing one to `position: absolute;` it is positioned correctly.

**Comment by FezVrasta** [comment] 2017-03-08 16:41
Wasn't the problem related to `translateY`? If you can fix the problem feel free to send a PR, but without a reproducible test case or an additional test in our test suite I can't really help you.

**Comment by nblackburn** [comment] 2017-03-08 16:42
@FezVrasta The other issue was but i feel this isn't the same thing anymore.

**Comment by FezVrasta** [comment] 2017-03-08 16:43
What a headache 🤕 Please open a new issue where I can reproduce the problem and I'll help you.

**Comment by nblackburn** [comment] 2017-03-08 16:47
@FezVrasta You are damn right, it's given me many trying to figure it out but it seems related to movement and position.
