### ISSUE TITLE
Position is wrong when body overflow is hidden and page is scrolled down

### ISSUE THREAD

**Issue by donnysim** [FezVrasta/popper.js#245] opened 2017-04-27 16:38 UTC
### CodePen demo

http://codepen.io/donnysim/pen/NjdoEb

### Steps to reproduce the problem

1.  Scroll down and click on the button

### What is the expected behavior?

The dropdown is below select.

### What went wrong?

Dropdown is way below of where it should be and jumps when the window height is adjusted.

**Comment by FezVrasta** [comment] 2017-04-27 16:43
May you please simplify the codepen to include only the minimum amount of code needed to reproduce the problem?

From my tests I noticed that if I set `.modal-open .modal` to `overflow: hidden` instead of `    overflow-x: hidden; overflow-y: auto;` everything works properly. But I need a more concise test case to better debug the problem.

**Comment by donnysim** [comment] 2017-04-27 16:44
I tried replicating what bootstrap does, but I'll see what I can change.

**Comment by donnysim** [comment] 2017-04-27 16:51
Well, this is the correct behavior. If you set `.modal-open .modal` to `overflow: hidden` then the modal itself will not be scrollable when the height is greater than window, so there's nothing else I can do.

**Comment by FezVrasta** [comment] 2017-04-27 16:53
I think I didn't explain myself clearly.

Your example includes a lot of 3rd party code (Bootstrap) and a lot of custom markup and CSS.

To be able to debug the problem I need an example as simple as possible, without any external dependency and with just the minimum code needed to reproduce the problem.

**Comment by FezVrasta** [comment] 2017-04-27 17:00
by the way, I tried to reproduce it from scratch. I think it's a dupe of #224

**Comment by donnysim** [comment] 2017-04-27 17:14
Removed bootstrap, but yeah, seems like it is :(

**Closed** 2017-04-27 17:15 UTC
Labels: # DUPLICATE
