### ISSUE TITLE
Tooltip in a parent container is in wrong position if parent is fixed position

### ISSUE THREAD

**Issue by JasonTheProgrammer** [FezVrasta/popper.js#250] opened 2017-05-05 04:32 UTC
### CodePen demo

http://codepen.io/JasonTheProgrammer/pen/mmMKrB

### Steps to reproduce the problem

1. Scroll down a little (200px is enough).
2. Click "Show Dialog".
3. Hover on the paragraph "Hover here".
4. Note that the tooltip is positioned too far above the paragraph. The further you've scrolled, the further away the tooltip.

### What is the expected behavior?

The tooltip should be positioned close to the text paragraph, and not be affected by the scroll position of the window.

### Comments

Originally I experienced this issue in an [Angular Material Dialog](https://material.angularjs.org/latest/demo/dialog). By default, a tooltip inside such a dialog gets truncated if it's larger than the dialog, so per the recommendation in #112 I opted to use the `container` option to specify a parent container. Doing that leads to the tooltip not being positioned correctly. In the linked CodePen I've reduced the scenario to the bare essentials without a dependency on Angular Material.

A workaround would be to *not* contain the tooltip in the parent element (easily tested using the checkbox), and remove `overflow: auto` from the CSS for `.dialog-content` to prevent the overflowing tooltip content being truncated. But my concern is the potentially unintended side-effects of that CSS change. This CSS is taken directly from Angular Material, and I have to assume it's there for a reason.

**Comment by FezVrasta** [comment] 2017-05-05 10:07
duplicate of #224

**Closed by FezVrasta** 2017-05-05 10:07 UTC
