### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by hsowan** [FezVrasta/popper.js#732] opened 2018-12-12 09:33 UTC
At `export default ve;`

**Comment by FezVrasta** [comment] 2018-12-12 09:34
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Closed by FezVrasta** 2018-12-12 09:34 UTC

**Comment by tassoman** [comment] 2019-01-12 19:49
Probably duplicate of #684 
If you're loading in the browser using `<script>` tag you need `dist/umd/*` files
