### ISSUE TITLE
Scrollbar appears when resizing window with right aligned popper

### ISSUE THREAD

**Issue by mariepw** [FezVrasta/popper.js#525] opened 2018-01-18 15:53 UTC
### CodePen demo

https://codepen.io/mariepw/pen/qpQQdO

### Steps to reproduce the problem

1.  Open the pen on a big window
2.  Resize the window horizontally

### What is the expected behavior?

The `#pop` should still be right aligned on the `#ref`

### What went wrong?

The `#pop` overflows to the right of the screen a horizontal scrollbar appears.

### Any other comments?

We decided to use `bottom-start` as a placement, because we use this in a dynamic menu that contains multiple dropdowns, and we don't know in advance which one is placed on the right of the screen.

The other dropdowns must have the menu aligned to the left when there is enough space.

**Comment by FezVrasta** [comment] 2018-01-18 16:01
duplicate of #251

**Closed by FezVrasta** 2018-01-18 16:01 UTC
