### ISSUE TITLE
Popper element partially placed outside of visible area on the right

### ISSUE THREAD

**Issue by s2hc-johan** [FezVrasta/popper.js#591] opened 2018-03-28 18:36 UTC
### CodePen demo

this jsfiddle https://jsfiddle.net/oou41czh/4/ shows the problem, when hidden, or when displayed and resized. 

### Steps to reproduce the problem

1.  create poppers that needs to be adjusted to the left to be visible
2.  set display: none on the poppers
3.  sohw the popper, and try to align it with popper.update()
4. see the error

### What is the expected behavior?

the popper being positioned correctly

### What went wrong?

the popper is partly hidden due to being placed outside of the visible area to the right.

### Any other comments?

if the display isn't none the popper get's positioned correctly, but resizing generates the same error.

**Comment by FezVrasta** [comment] 2018-03-28 18:47
Dupe of #251, sorry ☹️

**Closed by FezVrasta** 2018-03-28 18:47 UTC
