### ISSUE TITLE
Various questions regarding the position property.

### ISSUE THREAD

**Issue by QuentinLB** [FezVrasta/popper.js#198] opened 2017-04-07 13:02 UTC
Hi,

I am currently working on a quite complex UI with custom dropdown lists placed with popper.js and I have few issues and questions regarding the fixed vs. absolute positionning.

Here is my layout :

![image](https://cloud.githubusercontent.com/assets/6490070/24795745/b79475c8-1b8a-11e7-9879-a26e07a22081.png)

My two main issues :

1. When I setup a popper in the scrolling area (pink), it is lagging quite a lot during scrolls. The positionning is good but there is this one second lag that make the UX feel really sluggish. 
If I remove the `position: fixed;` on the page container (brown) the lag disappear but it messes up my layout. 
2. In nested absolutely positionned elements popper.js seems to get lost and put the popper in a wrong place.

I tried to replicate the conditions in a codepen https://codepen.io/anon/pen/ryEBmb but it is not lagging there.

Since I cannot provide much more information, I was wondering if the community could help me with some known issues or diagnosis.

On another note I was also wondering, why does the fixed position take priority on absolute positionning. What I mean is that if the popper has a common parent (relative) with the target it should use absolute. I am confident you did this for good reasons but by tweaking the position manually I achieve greater consistency especially in my second issue.

I am grateful for this is well rounded tool and thanks for looking into this. 👍

**Comment by FezVrasta** [comment] 2017-04-07 13:20
Hi, regarding the fixed vs absolute inside a fixed parent, the choice was made because usually (at least, in my case), fixed elements aren't scrollable (they are headers, sidebars etc) and then having a `fixed` position on the popper as well reduces the need for computations when the popper isn't child of the `fixed` element. I agree that this could be tweaked to make it behave differently to suite your use case.

About point 2, without a reproducible pen I can't help you to understand where's the problem unfortunately.

**Comment by QuentinLB** [comment] 2017-04-07 14:10
Thank you for your answer.

For the second point I made another pen but as for the previous one it is still not behaving as my app.
http://codepen.io/anon/pen/KWjMMj
In my app the popper is misplaced (overlapping)

I keep looking and I'll let you know if I find anything that could improve popper.

**Comment by FezVrasta** [comment] 2017-04-07 14:12
Unfortunately if you can't reproduce the problem on the pen I can't do anything 😥

**Comment by QuentinLB** [comment] 2017-04-07 14:32
I posted these just in case you recognized an anti-pattern or a known issue. Thank you though for taking a look at it.

**Comment by FezVrasta** [comment] 2017-04-07 14:33
Nope. I mean, Popper should work always in any possible case (this isn't the case because we have bugs, but the goal is this).

**Comment by FezVrasta** [comment] 2017-04-12 18:20
Update:

Point 1 should be fixed by #201, I'll take a look once the PR is stable.

**Comment by QuentinLB** [comment] 2017-04-12 21:31
Wonderfull, I will try it asap.

Just to let you know I fixed point 2 by allowing absolute positionning when there is a common parent relatively positioned between the popper and its target.

**Comment by FezVrasta** [comment] 2017-04-14 11:42
Please @QuentinLB try the latest pre release with:

```
npm i popper.js@next
```

And let me know if it fixes your problems.

**Comment by FezVrasta** [comment] 2017-04-14 13:11
Released as 1.5.1, we don't make use of `fixed` anymore so I expect all your problems to be solved.

Comment here if you still reproduce them and I'll reopen the issue.

**Closed by FezVrasta** 2017-04-14 13:11 UTC
Labels: # QUESTION
