### ISSUE TITLE
Offset not working as expected

### ISSUE THREAD

**Issue by mir3z** [FezVrasta/popper.js#557] opened 2018-02-14 12:14 UTC
### CodePen demo

https://codepen.io/anon/pen/aqyxXd

### Steps to reproduce the problem

1.  Use popper like in codepen and set offset that goes beyond ref element width/height

### What is the expected behavior?

Popper should be positioned using exact offset that I have specified.

### What went wrong?

Ref element has 100px height. I can make Popper if shifted beyoned that 100px. (use wtf1 offset in codepen)

### Any other comments?

In attached codepen I'm trying to position a "spotlight" - the circle that's supposed to point at defined elements of application during new users onboarding. CSS for spotlight is designed in the way that center of the spotlight is pointing exactly at given absolute top/left position.

**Comment by FezVrasta** [comment] 2018-02-14 12:27
That's the `keepTogether` modifier, I know it's quite confusing as default behavior... Must improve it in the next major version 🙄

https://codepen.io/FezVrasta/pen/BYdeQv

Closing as dupe of #230

**Closed by FezVrasta** 2018-02-14 12:27 UTC

**Comment by mir3z** [comment] 2018-02-15 10:24
Indeed, it's confusing. Anyway - thanks for help. ;)
