### ISSUE TITLE
Positioning incorrect when popper inside relatively or absolutely positioned parent

### ISSUE THREAD

**Issue by brentertz** [FezVrasta/popper.js#188] opened 2017-03-13 14:24 UTC
### CodePen demo

http://codepen.io/anon/pen/gmRRwz

### Steps to reproduce the problem

1. Instantiate a new popper, with default settings, inside of a relatively or absolutely positioned  parent.
2. Scroll or resize the page so that popper hits the bottom of the viewport, thus causing it to flip to the other side.

### What is the expected behavior?

Initial placement should be correct.

![screen shot 2017-03-13 at 8 18 46 am](https://cloud.githubusercontent.com/assets/202773/23858360/c437f972-07c5-11e7-87c6-5611a57db4ca.png)

The popper should flip to the opposite side of the target.

![screen shot 2017-03-13 at 8 14 14 am](https://cloud.githubusercontent.com/assets/202773/23858148/24a10ea8-07c5-11e7-9f70-8c89ce3003a6.png)

### What went wrong?

The initial placement is incorrect.

![screen shot 2017-03-13 at 8 17 47 am](https://cloud.githubusercontent.com/assets/202773/23858315/9fdc0ce4-07c5-11e7-80b3-bfd36cdd8282.png)

The popper flips, but the placement is incorrect.

![screen shot 2017-03-13 at 8 14 28 am](https://cloud.githubusercontent.com/assets/202773/23858156/2a49a388-07c5-11e7-8894-0716993dce87.png)

### Any other comments?

Not at this time.

**Comment by FezVrasta** [comment] 2017-03-13 15:10
This is caused by the default padding applied by Popper.js.

https://codepen.io/FezVrasta/pen/LWLzRP

**Comment by brentertz** [comment] 2017-03-13 17:00
In your latter codepen above, when the padding is removed and the flip activated, the popper is still placed over top of the reference element.

![screen shot 2017-03-13 at 10 46 25 am](https://cloud.githubusercontent.com/assets/202773/23865191/777d9b36-07da-11e7-91c9-91df89ac737f.png)

Surely not every container can be expected to have sufficient padding to allow a popper enough space to flip correctly.

FWIW, all of this flipping behavior/placement works as expected when `preventOverflow: { boundariesElement: 'viewport' }` is used, however I simply don't want the popper to stay in view when scrolled out of bounds.

I am unclear on what your suggestion is to work around this issue.  Can you perhaps provide a little more direction?

**Comment by FezVrasta** [comment] 2017-03-13 17:05
So, if you add a padding/margin to the body, things get messy because Popper takes the body as container of everything and it tries to avoid to make any popper overflow from it.

Actually I thought this issue was fixed with v1 but, hey, here it is 😅

I'm going to create a new issue to track it. Or feel free to create one if you prefer, I'm a bit busy atm.

**Comment by FezVrasta** [comment] 2017-03-13 17:15
by the way, this behavior is the correct and expected one:

![image](https://cloud.githubusercontent.com/assets/5382443/23866400/fd30d598-0818-11e7-83ab-9a0738db7d9b.png)

**Comment by FezVrasta** [comment] 2017-03-13 17:26
https://github.com/FezVrasta/popper.js/issues/189

**Comment by brentertz** [comment] 2017-03-13 17:42
Your comment above about the correct and expected behavior may be true when there is no more room at the top of the page/viewport, but it should not be the expected behavior when in the middle of a page and there is plenty of room above the target for the popper.  In that case, the popper should render entirely above the target.

See the following codepen and toggle the 2 different modifier configurations.

https://codepen.io/anon/pen/dvRmRz

**Comment by FezVrasta** [comment] 2017-03-13 17:48
Sorry I didn't noticed this problem.

By default `preventOverflow` should use as container its `scrollParent`, I fear it's taking the `offsetParent` instead for some reason?

https://github.com/FezVrasta/popper.js/blob/master/src/popper/modifiers/index.js#L53

**Comment by FezVrasta** [comment] 2017-03-14 15:27
So, I investigated a bit thanks to the test you added, looks like the problem is that `preventOverflow` is using the boundaries offset, that are relative to the document, together with the popper offsets, that are relative to its offset parent.

This situation should be normalized, making the boundaries relative to the popper's offsetParent, or making the popper offsets relative to the document.

I'm throwing here these info in case you (or someone else) want to prepare a PR to fix this behavior. I don't know when I will have some free time to dedicate to this bug unfortunately, since I'll be in the bay area for a week in a week and I've other priorities scheduled for this week.

**Comment by miljan-aleksic** [comment] 2017-04-02 21:30
@FezVrasta, I run into what seems the same issue. I am trying to implement Popper into Vuikit with UIkit 3, basically using it styles with popper js. As you can see in this [pen](https://codepen.io/miljan/pen/RpvMBP) the position `right` doesn't get placed on the right if the parent is relative. While the UIkit js does place it correctly.

You can edit the `.parent` style to check how it gets positioned as expected when is set as static.

**Comment by FezVrasta** [comment] 2017-04-06 12:01
@miljan-aleksic I don't think I'll have time to work on this in the near future, if you or anyone else want to adopt this issue please feel free and ask me anything you need to fix the bug.

**Comment by FezVrasta** [comment] 2017-04-09 14:36
So, I'm sharing here the work I'm doing to fix #188 and #171.

We need a way to find the common offset parent between popper and reference nodes, and this function I written seems to find it in a pretty elegant way:

```
function isOffsetContainer(element) {
  return element.firstElementChild.offsetParent === element
}

function findCommonOffsetParent(element1, element2) {
  const range = document.createRange();
  if (element1.compareDocumentPosition(element2) & Node.DOCUMENT_POSITION_FOLLOWING) {
    range.setStart(element1, 0);
    range.setEnd(element2, 0);
  } else {
    range.setStart(element2, 0);
    range.setEnd(element1, 0);
  }
  
  const { commonAncestorContainer } = range;
  
  if (isOffsetContainer(commonAncestorContainer)) {
    return commonAncestorContainer;
  }
  
  return commonAncestorContainer.offsetParent;
}
```

Now I'm trying to rewrite the core of Popper to use this stuff...

**Closed** 2017-04-14 11:38 UTC
Labels: # BUG, DIFFICULTY: HARD, PRIORITY: HIGH

**Comment by brentertz** [comment] 2017-04-14 13:08
Nice work!  I can confirm that `popper.js@next` fixes the issue in my aforementioned codepens.

**Comment by nblackburn** [comment] 2017-04-14 17:06
Fixes my problems also, thanks for all your hard work 🥇

**Comment by ChrisGao2016** [comment] 2018-12-27 13:02
@FezVrasta 
I read the code of popper.js recently. I found you change the algorithm of getting the reference position after the 1.0.8 version.  I  think the original algorithm still works in this case.  when the boundariesNode of popper  is  body. You didn't calculate the offset that from boundariesNode to the offsetParent of popper is the cause of the problem.
You could change the code in the  getBoundaries function to fix this bug. when the boundariesElement is not 'viewport',  always run this line of code:
` boundaries = getOffsetRectRelativeToCustomParent(boundariesNode, offsetParent, isFixed(popper));`

**Comment by FezVrasta** [comment] 2018-12-27 13:09
@ChrisGao2016 please may you send a PR adding a failing test case for this issue? I thought it was fixed

**Comment by ChrisGao2016** [comment] 2018-12-27 13:22
@FezVrasta The new algorithm is nice. so the PR of old version has little meaning.  Thanks for your wonderful code of popper.js.
