### ISSUE TITLE
Position issue with 100% height body 

### ISSUE THREAD

**Issue by sean8415** [FezVrasta/popper.js#388] opened 2017-08-15 05:16 UTC
Hi,

Thanks for the great plugin. However I have encountered 2 issues:

1) When the body tag uses 100% height the position of the most bottom element's poppers are calculated wrongly(v1.9.3 does not have this issue.)

2) When i use v1.9.3 as a workaround for the above issue I got this issue. I hope this issue was fixed after v1.9.3 

Thanks.

**Comment by FezVrasta** [comment] 2017-08-15 06:53
Dupe of #302

**Closed by FezVrasta** 2017-08-15 06:53 UTC
