### ISSUE TITLE
Popper placed on wrong side when reference is inside positioned parent

### ISSUE THREAD

**Issue by atomiks** [FezVrasta/popper.js#621] opened 2018-04-20 06:04 UTC
Reported here: https://github.com/atomiks/tippyjs/issues/228

### CodePen demo

https://codepen.io/anon/pen/aGOvmj

### What is the expected behavior?

Popper is on the left

### What went wrong?

Popper appears on the right

is fixed with

```js
modifiers: {
  preventOverflow: {
    enabled: false
  },
  hide: {
    enabled: false
  }
}
```

### Any other comments?

`position: absolute/fixed` creates a different positioning context I guess so it thinks it's near the edge of the document/viewport

Is this expected behavior?

**Comment by FezVrasta** [comment] 2018-04-27 16:33
You have a `overflow-x: auto` which creates a new `scrollParent` for Popper.js.

This seems a dupe of https://github.com/FezVrasta/popper.js/issues/611

**Closed by FezVrasta** 2018-04-27 16:33 UTC
