### ISSUE TITLE
Tooltip sometimes disappears even if mouse pointer is over it

### ISSUE THREAD

**Issue by aleksanderd** [FezVrasta/popper.js#718] opened 2018-11-19 16:01 UTC
### CodePen demo

https://codepen.io/aleksanderd/pen/VVrZOj

### Steps to reproduce the problem

1.  move pointer to the red, await for the tip displayed
2.  move mouse to the tip slowly for triggering mouseout, but it must take less then 1s (delay param), so the pointer must be in tip element.
3.  the tip will be hidden

### What is the expected behavior?

the tip must not be hidden, since the pointer is over it.

### Any other comments?

presumably, since there is a space between ref and tip, mouse moving here cause a `mouseout` event which leads to `sheduledHide`.

**Comment by FezVrasta** [comment] 2018-11-19 16:02
dupe of #669

**Closed by FezVrasta** 2018-11-19 16:02 UTC
