### ISSUE TITLE
keepTogether doesn't avoid popper from float away from its reference element

### ISSUE THREAD

**Issue by lukebatchelor** [FezVrasta/popper.js#75] opened 2016-08-19 05:10 UTC
### CodePen demo

No codepen needed, problem reproducible on https://popper.js.org/
### Steps to reproduce the problem
1.  Go to https://popper.js.org/
2.  Scroll down the page
### What is the expected behavior?

The "Popper on bottom" popper to flow smoothly
### What went wrong?

It has some weird jankyness
### Any other comments?

Not sure if its a huge issue or not but thought I'd bring it to your attention.

Happening in Chrome Version 52.0.2743.116 (64-bit) on Mac OSX 10.11.4 scrolling with touch gestures on a Mac Magic Trackpad. 

Give me a yell if you need any help reproducing. (Love this library btw, looking into the v1 docs now!)

![](http://i.imgur.com/UxjIWZ9.gif)

**Comment by FezVrasta** [comment] 2016-08-19 06:58
Thanks, something is definitely wrong. Gonna fix it ASAP

**Comment by FezVrasta** [comment] 2016-08-19 08:54
Ok it was a problem with the CDN, the gh-pages was asking for the latest version of popper.js, and so the demo page switched to the v1.0.0-apha.2 version, but the demo page is not yet updated to use this version. Now I forced the page to use the v0.*

**Comment by FezVrasta** [comment] 2016-10-10 10:23
Reopening since this is an actual bug with the version 1.

We modified `keepTogether` to work only on the main axis, but doing so, when we set as `boundariesElement` `viewport`, the popper will float away from its reference element when the reference element is not inside the viewport.

Two possible solutions:

1. Make `keepTogether` read the offset from the `offset` modifier and make it allow only the specified offset.
2. Modify the `boundariesElement` behavior:

right now we use `boundariesElement` to calculate the offsets and to make the `flip` modifier work. We may implicity calculate the offsets based on the `scrollParent` and convert `boundariesElement` to a `flip` modifier property to make it work as expected.

Solution 1 is much easier, but probably 2 is the way to go in long term.

@AndreaScn @nadiam84 thoughts?

**Comment by FezVrasta** [comment] 2016-10-10 10:30
This is related to #59, we want to address them together.

**Comment by FezVrasta** [comment] 2016-10-10 10:38
@AndreaScn assigning it to you since #59 have been closed in favor of this one. If you can find some time to work on this it would be really awesome, this is a critical high priority issue to be able to release v1.

**Comment by nadiam84** [comment] 2016-10-11 00:45
For me it feels like the fix should be in keepTogether modifier, since it's responsible for the 'keep together' behavior. Logically. So I vote for the solution 1. :)

**Comment by FezVrasta** [comment] 2016-10-11 10:29
Solution 1 is more a patch then a solution. We'll still have to implement the `scrollParent` option for `boundariesElement` that will then be required in almost all the cases (making `viewport` and `window` useless). 😕

**Comment by FezVrasta** [comment] 2016-10-18 10:02
I added a test to reproduce this bug:
https://github.com/FezVrasta/popper.js/commit/6268d0b0358e6721d18f85ca21e2267f40834a3f

**Comment by FezVrasta** [comment] 2016-10-18 11:16
I'm working on it, almost done.

The flip modifier now detects the flip needs checking the boundaries (smart method) instead of relying on preventOverflow.

**Comment by FezVrasta** [comment] 2016-11-07 13:45
Fixed on `v1-dev`.

**Closed by FezVrasta** 2016-11-07 13:45 UTC
Labels: BUG, DEBUGGED, MODIFIER, WIP
