### ISSUE TITLE
position: sticky?

### ISSUE THREAD

**Issue by leeoniya** [FezVrasta/popper.js#140] opened 2017-01-09 18:57 UTC
Hey @FezVrasta 

I was wondering if there's any known example/demo/plugin for popper.js that can be used in a manner similar to https://github.com/wilddeer/stickyfill

It seems like an ideal use-case for a positioning engine and would help reduce dependencies on multiple libs that have 80% overlap in positioning functionality.

thanks!

**Comment by FezVrasta** [comment] 2017-01-09 19:04
This isn't something I would put in the core library, probably a modifier could be created to achieve this result. I can't see a strict correlation between the two though, but maybe because I don't know how stickyfill works.

**Comment by leeoniya** [comment] 2017-01-09 19:09
> This isn't something I would put in the core library, probably a modifier could be created to achieve this result.

Right, that makes sense. That's why i asked if there was some external example or plugin/modifier.

> I can't see a strict correlation between the two though, but maybe because I don't know how stickyfill works.

Stickyfill probably isnt a good demo of the more generalized case. Perhaps this alternative [1] [2] better illustrates the similarity to popper.js:

[1] https://github.com/filamentgroup/fixed-sticky
[2] http://filamentgroup.github.io/fixed-sticky/demos/demo.html

**Comment by FezVrasta** [comment] 2017-01-09 19:16
Seems like my brain doesn't want to turn on while I read these info... Must be that it's 8pm here and I worked on coding stuff the whole day 😅

The first problem I see is that `sticky` doesn't refer to any reference element to position itself, so you would have to provide a set of coordinates to emulate a reference element. This isn't something supported right now, mostly because I rely on the reference element context to understand how the popper will behave.

**Comment by FezVrasta** [comment] 2017-01-11 11:26
Since it's not a bug nor something worth to add to the core I'm closing the issue, this doesn't mean I don't want to continue the conversation, it's just to keep the issues list clean.

Feel free to continue here or on Gitter if you prefer.

**Closed by FezVrasta** 2017-01-11 11:26 UTC
Labels: QUESTION
